#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        4
bspc config window_gap          0

bspc config top_padding 14
bspc config split_ratio          0.52
bspc config active_border_color '#0C1115'
bspc config normal_border_color '#0C1115'
bspc config focused_border_color '#928374'
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop=^2
bspc rule -a Firefox floating=off desktop=^2
bspc rule -a qutebrowser desktop=^2
bspc rule -a Firefox floating=off desktop=^2
bspc rule -a URxvt:main desktop=^1
bspc rule -a URxvt:ranger floating=off desktop=^4
bspc rule -a URxvt:ncmpcpp floating=off desktop=^5
bspc rule -a URxvt:alsamixer floating=off desktop=^5
bspc rule -a URxvt:newsbeuter floating=off desktop=^6
bspc rule -a URxvt:rtorrent desktop=^9
bspc rule -a URxvt:cprogram desktop=^4
bspc rule -a Zathura floating=off desktop=^4
bspc rule -a sun-awt-X11-XDialogPeer state=floating


## AutoStart
##panel2 &
polybar mybar &
mpd &
urxvt -name main -title main &
urxvt -name ncmpcpp    -title ncmpcpp -e ncmpcpp &
urxvt -name ncmpcpp    -e ncmpcpp -s visualizer &
urxvt -name ncmpcpp     -e ncmpcpp -s browser &
urxvt -name ranger     -e ranger            &
urxvt -name rtorrent    -e rtorrent &
urxvt -name newsbeuter -e newsbeuter  &
zathura /home/deadsec/Documents/andy.pdf &
